config/routes.rb
Rails.application.routes.draw do
  # READER ROUTES

  devise_for :readers

  resources :articles do
    member do
      put 'like' => 'articles#vote'
    end
  end

  get 'history' => 'articles#history'
  get 'friends' => 'articles#friends'

  get 'readers/:reader_id/articles' => 'articles#index_personal', as: 'personal_articles'
  get 'readers/:reader_id/articles/:article_id' => 'personal_articles#show', as: 'personal_article'

  # ADMIN ROUTES

  devise_for :admins

  resources :statistics

  get 'statistics/readers/:reader_id' => 'statistics#readers', as: 'statistics_reader'
  get 'statistics/readers/:reader_id/preferences/:preference_id' => 'statistics#preferences', as: 'statistics_reader_preference'
  get 'statistics/readers/:reader_id/preferences/:preference_id/keywords/:keyword_id' => 'statistics#keywords', as: 'statistics_reader_keyword'

  # ROOT PATH

  root 'articles#index'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id                      :integer          not null, primary key
#  headline                :string
#  subheading              :text
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  views                   :integer          default(0), not null
#  likes                   :integer          default(0), not null
#  category_id             :integer
#  cached_votes_total      :integer          default(0)
#  cached_votes_score      :integer          default(0)
#  cached_votes_up         :integer          default(0)
#  cached_votes_down       :integer          default(0)
#  cached_weighted_score   :integer          default(0)
#  cached_weighted_total   :integer          default(0)
#  cached_weighted_average :float            default(0.0)
#  img_src                 :string
#  body_text               :text
#  api_id                  :string
#  publication_date        :datetime
#  reader_id               :integer
#  rank                    :float            default(0.0), not null
#

class Article < ApplicationRecord
  acts_as_votable

  belongs_to :category
  has_many :orders
  has_many :readers, through: :orders
  has_many :keywords, as: :word

  validates_uniqueness_of :api_id, scope: :reader_id
  validates :rank, inclusion: { in: 0..100 }
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :find_article, only: %i[show vote]
  before_action :find_reader, only: %i[index_personal]
  before_action :require_login
  respond_to :js, :json, :html

  def index
    @title = 'Homepage'
    @orders = current_reader.orders.all.order(created_at: :desc)

    if params[:category].blank? && params[:topic].blank?
      @articles = Article.where(reader_id: nil).order(publication_date: :desc)
    elsif params[:category] == 'Top Trending'
      @title = 'Homepage - Trending'
      @trending = Keyword.where(word_type: 'Preference').group(:name).sum(:relevance).sort_by { |_name, relevance, _id| relevance }.reverse[0..50]
      @analyzer = StatisticsHelper::Analyzer.new
    elsif !params[:topic].blank?
      @articles = []
      @topics = Keyword.where(word_type: 'Article').where(name: params[:topic].capitalize)
      @topics.each do |topic|
        @articles.push Article.find(topic.word_id)
      end
      @articles = @articles.sort_by { |e| e[:publication_date] }.reverse
    elsif params[:category] != 'Top Trending' && params[:topic].blank?
      @title = "Homepage - #{params[:category]}"
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.select('DISTINCT ON (publication_date, api_id,headline) *').where(category_id: @category_id).order(publication_date: :desc)
    end
  end

  def index_personal
    @title = 'For You'
    @orders = current_reader.orders.all.order(created_at: :desc)
    @articles = Article.where(reader_id: @reader.id)
  end

  def show
    @title = @article.headline

    @related_articles = Article
                        .where(category_id: @article.category_id)
                        .where.not(api_id: @article.api_id)
                        .order(publication_date: :desc)
                        .limit(9)
    @better_related_articles = @related_articles.select('DISTINCT ON (publication_date, api_id,headline) *')
    @related_category = Category.find(@article.category_id).name

    if reader_signed_in?
      if current_reader.orders.where(article_id: @article.id).blank?

        @article.increment!(:views)

        current_reader.orders.create(article_id: @article.id, article_url: @article.api_id, reader_id: current_reader.id, category_id: @article.category_id, created_at: Time.now, updated_at: Time.now)

        Category.find(@article.category_id).increment!(:relevance)

        @keywords = @article.keywords.all

        current_reader.preferences.create(category: @related_category, created_at: Time.now, updated_at: Time.now)
        current_reader.preferences.find_by(category: @related_category).increment!(:relevance)

        @keywords.each do |keyword|
          next if keyword == @related_category

          current_reader.preferences.find_by(category: @related_category).keywords.create(name: keyword.name, tag: keyword.tag, reader_id: current_reader.id, category_id: @article.category_id, created_at: Time.now, updated_at: Time.now)
          word = current_reader.preferences.find_by(category: @related_category).keywords.find_by(name: keyword.name)
          KeywordStatistic.create(keyword_id: word.id, name: word.name, created_at: Time.now)

          unless word.nil?
            word.relevance += 1
            word.save
          end
        end
      end
    end
  end

  def vote
    if !current_reader.liked? @article

      @article.liked_by current_reader
      @keywords = @article.keywords.all
      @related_category = Category.find(@article.category_id).name
      current_reader.preferences.find_by(category: @related_category).increment!(:relevance)

      @keywords.each do |keyword|
        next if keyword == @related_category

        word = current_reader.preferences.find_by(category: @related_category).keywords.find_by(name: keyword.name)

        unless word.nil?
          word.relevance += 1
          word.save
        end
      end

    elsif current_reader.liked? @article

      @article.unliked_by current_reader

    end
  end

  def history
    @title = 'History'

    @order = current_reader.orders.all.order(created_at: :desc)

    # Retrives all orders and divides into two groups today's orders and other day's orders
    @grouped_orders = @order.group_by { |t| t.created_at.to_date == DateTime.now.to_date }

    if @grouped_orders[false].present?
      # Create day wise groups of orders
      @day_wise_sorted_orders = @grouped_orders[false].group_by { |t| t.created_at.strftime("%A #{t.created_at.day.ordinalize} %B, %Y ") }
    end

    @liked_articles = []

    @all_articles = Article.all.order(created_at: :desc)

    @all_articles.each do |article|
      @liked_articles.push article if current_reader.voted_for? article
    end
  end

  def friends
    analyzer = StatisticsHelper::Analyzer.new
    ranker = ArticlesHelper::Ranker.new

    @title = 'Homepage - Friends'

    analyzer.compute_similarity(current_reader.friendships)

    @friendships = current_reader.friendships.where("similarity > ?", 25).order(similarity: :desc).limit(3)

    @suggested_orders, @ranks = [],[]
    
    @friendships.each do |friendship|
      reader = Reader.find(friendship.friend_id)
      reader_orders = reader.orders.all.order(created_at: :desc)

      reader_orders.each do |order|
        article = Article.find(order.article_id)
        
        unless current_reader.orders.find_by(article_id: order.article_id) || order.created_at < 2.days.ago 
          
          rank = ranker.what_rank(article, current_reader)
          if rank > 5
            @suggested_orders << order
            @ranks << rank
          end

        end
      end
    end

  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def find_reader
    @reader = Reader.find(params[:reader_id])
  end

  def require_login
    redirect_to new_reader_session_path unless reader_signed_in?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    class Ranker

        def rank(article, reader)

            rank = 0.0
            category_rank = 0.0
            keyword_rank = 0.0
            counter = 0

            category = Category.find(article.category_id).name
            keywords = article.keywords

            matched_category = reader.preferences.find_by(category: category)
            preference_keywords = Keyword.where(reader_id: reader.id).group(:name).sum(:preferencial_score)

            unless matched_category.nil?
                # We have a match! Increase Rank!
                category_rank += matched_category.preferencial_score
            end

            preference_keywords.keys.each_with_index do |key, index|

                if keywords.find_by(name: key)
                    # We have a match! Increase Rank!
                    keyword_rank += preference_keywords.values[index]
                    counter += 1
                end

            end

            final_rank = ((category_rank + (keyword_rank / counter)) / 2).round(2)

            if final_rank.nan?
                
                article.rank = 0.0
                article.save

            else

                article.rank = final_rank
                article.save

            end
            
        end

        def what_rank(article, reader)

            rank = 0.0
            category_rank = 0.0
            keyword_rank = 0.0
            counter = 0

            category = Category.find(article.category_id).name
            keywords = article.keywords

            matched_category = reader.preferences.find_by(category: category)
            preference_keywords = Keyword.where(reader_id: reader.id).group(:name).sum(:preferencial_score)

            unless matched_category.nil?
                # We have a match! Increase Rank!
                category_rank += matched_category.preferencial_score
            end

            preference_keywords.keys.each_with_index do |key, index|

                if keywords.find_by(name: key)
                    # We have a match! Increase Rank!
                    keyword_rank += preference_keywords.values[index]
                    counter += 1
                end

            end

            return ((category_rank + (keyword_rank / counter)) / 2).round(2)
        end
    end
end

app/views/articles/friends.html.erb
<h1 class="current-category" style="font-weight: bold;">Similar users to you</h1>

<div class="row">

    <% @orders = current_reader.orders.all %>

    <% @friendships.each do |friendship| %>

        <% @reader = Reader.find(friendship.friend_id) %>

        <% @similarity = friendship.similarity.to_i%>

            <!-- Friend Bar -->

            <div class="col-md-6">

                <br><br>

                <% if @suggested_orders.any? {|orders| orders.reader_id == @reader.id } %>

                    <div class="col-md-12 col-md-offset-1">

                        <div class="friend-bar">
                            <div class="friend-image">
                                <div class="donut">    
                                    <%= pie_chart [["Match", @similarity], ["", 100-@similarity]], donut: true, library: {animation: {easing: 'easeOutQuad'}, backgroundColor: "transparent", elements: {arc: {borderWidth: 0}}},legend: false, width: "85px", height: "85px", colors: ["#52f2a7","transparent"] %>
                                </div>
                                <h6 class="similarity-text"><%=@similarity%>% Match</h6>
                                <%= image_tag @reader.avatar, class: "avatar-friend" %>
                            </div>
                            <div class="friend-bar-text">
                                <h3 class="friend-name"><%= @reader.name %>'s</h3>
                                <p class="friend-name">Top recommendations for you</p>
                            </div>
                        </div>
                    
                        <br>

                    </div>
            
                    <div class="col-md-12 col-md-offset-1" style="margin-bottom: 10px;">

                        <% @suggested_orders.each_with_index do |order, index| %>

                            <% if order.reader_id == @reader.id %>
                    
                                <% @article = Article.find(order.article_id) %>
                    
                                <div class="col-md-3 article-box-history" onclick="location.href='/articles/<%= @article.id %>';" style="cursor: pointer;">
                                    <a href="/articles/<%= @article.id %>" class="a-article">
                                        <%= image_tag @article.img_src, class: "article_img-history", style:"margin-top:14px;" %>
                                    </a>
                                    <h6 class="article-headline-history"><%= @article.headline %></h6>
                                    <div class="article-mini-date" style="width: 85%; position: absolute; bottom: 7px; text-transform: uppercase; font-size: 14px; color:gray;">
                                        <div style="font-size: 10px; text-align:center;">
                                            <% if @ranks[index] >= 30 %>
                                                <span style="color: #0ce87b; float: right; text-transform: capitalize;"><b>Suggested</b></span>
                                            <% elsif @ranks[index] < 30 && @ranks[index] >= 15 %>
                                                <span style="color: #e8c70c; float: right; text-transform: capitalize;"><b>Suggested</b></span>
                                            <% elsif @ranks[index] < 15 %>
                                                <span style="color: #e86f0c; float: right; text-transform: capitalize;"><b>Suggested</b></span>
                                            <% end %>
                                        </div>
                                    </div>
                    
                                </div>
                    
                            <% end %>        
                        
                        <% end %>

                    </div>

                <% end %>

            </div>

    <% end %> 

</div>

app/views/articles/history.html.erb
<!-- Left Column -->

<div class="col-md-6 article-history-left-panel">

    <h1 class="current-category">History</h1>

    <!-- Read Today articles -->

    <% if @grouped_orders.present? && @grouped_orders[true].present? %>
    
        <div class="col-md-12" style="margin-bottom: 10px;">

            <h4> Today </h4>

            <% @grouped_orders[true].take(4).each do |order| %>

                <div class="col-md-3 article-box-history" onclick="location.href='/articles/<%= Article.find(order.article_id).id %>';" style="cursor: pointer;">
                    <a href="/articles/<%= Article.find(order.article_id).id %>" class="a-article">
                        <%= image_tag Article.find(order.article_id).img_src, class: "article_img-history", style: "margin-top: 14px;" %>
                    </a>
                    <h6 class="article-headline-history"><%= Article.find(order.article_id).headline %></h6>
                </div>

            <% end %> 

        </div>

    <% end %>

    <!-- Day wise grouped articles -->

    <% if @day_wise_sorted_orders.present? %>

        <% @day_wise_sorted_orders.each do |hash_elements|%>

            <div class="col-md-12" style="margin-bottom: 10px;">

                <h4> <%= hash_elements.first %> </h4>

                <% hash_elements.last.take(4).each do |order| %>

                    <div class="col-md-3 article-box-history" onclick="location.href='/articles/<%= Article.find(order.article_id).id %>';" style="cursor: pointer;">
                        <a href="/articles/<%= Article.find(order.article_id).id %>" class="a-article">
                            <%= image_tag Article.find(order.article_id).img_src, class: "article_img-history", style:"margin-top: 14px;" %>
                        </a>
                        <h6 class="article-headline-history"><%= Article.find(order.article_id).headline %></h6>
                       
                    </div>
                    
                <% end %> 

            </div>

        <% end %>

    <% end %>

</div>

<!-- Right Column -->

<div class="col-md-6 article-history-right-panel">
    
    <h1 class="current-category">Liked Articles</h1>

    <% @liked_articles.take(8).each do |article| %>

        <div class="col-md-3 article-box-history" onclick="location.href='/articles/<%= article.id %>';" style="cursor: pointer;">
            <a href="/articles/<%= article.id %>" class="a-article" >
                <%= image_tag article.img_src, class: "article_img-history", style:"margin-top: 14px;" %>
            </a>
            <h6 class="article-headline-history"><%= article.headline %></h6>
        </div>

    <% end %>

</div>

app/views/articles/index.html.erb
<% if params[:category].blank? && params[:topic].blank? %>
    <h1 class="current-category" style="font-weight: bold;">All Articles</h1>    
<% end %>

<% unless params[:category] == "Top Trending" || !params[:topic].blank? %>
    <h1 class="current-category" style="font-weight: bold;"><%= params[:category] %></h1>
    <div class="row justify-content-center">

        <% @articles.each do |article| %>

            <% unless @orders.find_by(article_id: article.id) %>

                <div class="col-md-3 col-md-offset-1 article-box" onclick="location.href='/articles/<%= article.id %>';" style="cursor: pointer;">
                    <a href="/articles/<%= article.id %>" class="a-article">
                        <%= image_tag article.img_src, class: "article_img" %>
                    </a>
                    
                    <h4 class="article-headline"><%= article.headline %></h4>
                    
                    <div class="article-mini-date" style="width: 85%; position: absolute; bottom: 0px; text-transform: uppercase; font-size: 14px; color:gray;">
                        <p>
                            <%= Category.find(article.category_id).name %>
                            
                            <% if article.created_at > current_reader.last_sign_in_at && @orders.find_by(article_id: article.id).nil? %>
                                <span style="color: #f81848; float: right;"><i class="fab fa-hotjar"></i> New</span>
                            <% end %>
                        </p>
                    </div>

                </div>

            <% end %>

        <% end %>

    </div>
<% end %>


<% if params[:category] == "Top Trending" %>
    
    <div class="row" style="margin-left: 7px;">

        <h1 class="current-category" style="font-weight: bold;">Trending Now</h1>

        <div class="search">
            <%= form_tag(articles_path, method: :get, class:'navbar-form') do %>
                <div class="input-group" style="width: 300px;margin: 10px 0px 15px 15px;">
                    <%= text_field_tag :topic, "" ,class:"form-control pull-right", style:"border: 1px solid #c0c0c0; background-color: #ffffff;", placeholder: "Search for a topic" %>
                    <span class="input-group-btn">
                        <%= button_tag '', class:"btn btn-default", name: nil do %>
                            <span class="glyphicon glyphicon-search">
                                <span class="sr-only">Search</span>
                            </span>
                        <% end %>
                    </span>
                </div>
            <% end %>
        </div>

        <div class="col-md-4" style="margin-left: 0px;">
            
            <h3 style="margin-bottom: 30px;">Categories</h3>

            <% Category.order(preferencial_score: :desc).limit(5).each do |category|%>

                <div class="preference-box word-box" onclick="location.href='/articles?category=<%=category.name%>';">
                    <h4 class="preference-name category" style="color:#a33cf7"><%= link_to category.name, articles_path(category: category.name), class: "article-mini-preference", style: "font-weight: 400;" %></h4>
                </div>  

            <% end %>

        </div>

        <div class="col-md-4 col-md-offset-2" >

            <h3 style="margin-bottom: 30px;">Topics</h3>

            <% counter = 0 %>

            <% @trending.take(10).each do |topic| %>

                <% if @analyzer.trending(topic.first) %>

                    <div class="preference-box word-box" onclick="location.href='/articles?topic=<%=topic.first%>';">
                        <h4 class="preference-name category"><%= link_to topic.first, articles_path(topic: topic.first), class: "article-mini-category", style: "font-weight: 400;" %></h4>
                    </div>  

                    <% counter += 1 %>

                <% end %>

            <% end %>

            <% if counter == 0 %>
                    
                <h5> There are no trending topics at the moment. </h5>

            <% end %>

        </div>

    </div>

    <div class="row" style="margin-top: 50px; margin-left: 7px;">

        <h1 class="current-category" style="font-weight: bold;">Top Chart</h1>

        <div class="col-md-4" style="margin-left: 0px;">

            <h3 style="margin-bottom: 30px;">Topics</h3>

            <% @trending.take(10).each do |topic| %>

                <div class="preference-box word-box" onclick="location.href='/articles?topic=<%=topic.first%>';">
                    <h4 class="preference-name category"><%= link_to topic.first, articles_path(topic: topic.first), class: "article-mini-top", style: "font-weight: 400;" %></h4>
                </div>  

            <% end %>
    
        </div>
    </div>

<% end %>

<% if !params[:topic].blank? %>
    <h1 class="current-category" style="font-weight: bold;"><%= params[:topic].capitalize %></h1>
    <div class="row justify-content-center">

        <% @articles.uniq { |i| i.api_id }.each do |article| %>

            <% unless @orders.find_by(article_id: article.id) %>

                <div class="col-md-3 col-md-offset-1 article-box" onclick="location.href='/articles/<%= article.id %>';" style="cursor: pointer;">
                    <a href="/articles/<%= article.id %>" class="a-article">
                        <%= image_tag article.img_src, class: "article_img" %>
                    </a>
                    
                    <h4 class="article-headline"><%= article.headline %></h4>
                    
                    <div class="article-mini-date" style="width: 85%; position: absolute; bottom: 0px; text-transform: uppercase; font-size: 14px; color:gray;">
                        <p>
                            <%= Category.find(article.category_id).name %>
                            
                            <% if article.created_at > current_reader.last_sign_in_at && @orders.find_by(article_id: article.id).nil? %>
                                <span style="color: #f81848; float: right;"><i class="fab fa-hotjar"></i> New</span>
                            <% end %>
                        </p>
                    </div>

                </div>

            <% end %>

        <% end %>

    </div>
<% end %>

app/views/articles/index_personal.html.erb
<% if !@articles.empty? %>

    <h1 class="current-category" style="font-weight: bold;">Picked Articles just for 
        <strong class="red-word">You
        </strong>
    </h1>    

    <div class="row justify-content-center">

        <% @articles.where("rank > ?", 25).order(created_at: :desc, rank: :desc).each do |article| %>

            <% unless @orders.find_by(article_id: article.id) %>

                <div class="col-md-3 col-md-offset-1 article-box" onclick="location.href='/articles/<%= article.id %>';" style="cursor: pointer;">
                    <a href="/articles/<%= article.id %>" class="a-article">
                        <%= image_tag article.img_src, class: "article_img" %>
                    </a>
                    
                    <h4 class="article-headline"><%= article.headline %></h4>

                    <div class="article-mini-date" style="width: 85%; position: absolute; bottom: 7px; text-transform: uppercase; font-size: 14px; color:gray;">
                        <div style="font-size: 12px; text-align:center;">
                            <span style="float:left;"><%= Category.find(article.category_id).name %></span>
                            <% if article.rank >= 50 %>
                                <span style="color: #0ce87b; float: right; text-transform: capitalize;"><b><%= article.rank.to_i %>% Match</b></span>
                            <% elsif article.rank < 50 && article.rank >= 30 %>
                                <span style="color: #e8c70c; float: right; text-transform: capitalize;"><b><%= article.rank.to_i %>% Match</b></span>
                            <% elsif article.rank < 30 %>
                                <span style="color: #e86f0c; float: right; text-transform: capitalize;"><b><%= article.rank.to_i %>% Match</b></span>
                            <% end %>
                            <% if article.created_at > current_reader.last_sign_in_at %>
                                <span style="color: #f81848;"><i class="fab fa-hotjar"></i> New</span>
                            <% end %>
                        </div>
                    </div>
                </div>

            <% end %>

        <% end %>

    </div>

<% else %>

    <h1 class="current-category" style="font-weight: bold;">Start reading some articles</h1>   
  
<% end %>

app/views/articles/saved.html.erb
 
<div class="col-md-6 article-history-left-panel">

    <h1 class="current-category">History</h1>

    <!-- Read Today articles -->

    <% if @grouped_orders.present? && @grouped_orders[true].present? %>
    
        <div class="col-md-12" style="margin-bottom: 10px;">

            <h4> Today </h4>

            <% @grouped_orders[true].each do |order| %>

                <div class="col-md-3 article-box-history" onclick="location.href='/articles/<%= Article.find(order.article_id).id %>';" style="cursor: pointer;">
                    <h5 class="article-headline-history"><%= Article.find(order.article_id).headline %></h5>
                    <a href="/articles/<%= Article.find(order.article_id).id %>" class="a-article">
                        <%= image_tag Article.find(order.article_id).article_img.url(:article_index), class: "article_img-history" %>
                    </a>
                </div>

            <% end %> 

        </div>

    <% end %>

    <!-- Day wise grouped articles -->

    <% if @day_wise_sorted_orders.present? %>

        <% @day_wise_sorted_orders.each do |hash_elements|%>

            <div class="col-md-12" style="margin-bottom: 10px;">

                <h4> <%= hash_elements.first %> </h4>

                <% hash_elements.last.take(4).each do |order| %>

                    <div class="col-md-3 article-box-history" onclick="location.href='/articles/<%= Article.find(order.article_id).id %>';" style="cursor: pointer;">
                        <h5 class="article-headline-history"><%= Article.find(order.article_id).headline %></h5>
                        <a href="/articles/<%= Article.find(order.article_id).id %>" class="a-article">
                            <%= image_tag Article.find(order.article_id).article_img.url(:article_index), class: "article_img-history" %>
                        </a>
                    </div>
                    
                <% end %> 

            </div>

        <% end %>

    <% end %>

</div>

app/views/articles/show.html.erb
<!-- ARTICLE -->

<div class="row row-article-content article-info">

    <!-- LEFT PANEL -->

    <div class="col-md-7 article-left-panel">
        <h2 style="padding-bottom: 10px;"><%= @article.headline %></h2>
        <%= image_tag @article.img_src, class: "article-show" %>
        <h4 style="font-weight: 500; padding-top: 10px; font-size: 17px;"><%= @article.subheading %></h4>
        <br>
        <h5> <%= @article.publication_date.strftime("%A #{@article.publication_date.day.ordinalize} %B, %Y ") %></h5>
        <br>
        <p class="article-body-text" style="font-size: 17px"> <%= @article.body_text %> </p>

        <br>
        
        <% if reader_signed_in? %>

            <%= link_to like_article_path(@article), class:"like-btn liked", method: :put, remote: :true do %>
                <button type="button" class="btn-like-custom" aria-label="Left Align">
                    
                    <% if current_reader.liked? @article %>
                        <span class="fas fa-heart" id="showhide-heart" aria-hidden="true"></span>
                    <% else %>    
                        <span class="far fa-heart" id="showhide-heart" aria-hidden="true"></span>
                    <% end %>
                    
                    <span class="likes-count" style="font-size: 15px; font-weight: 400;"><%= @article.cached_votes_score %></span>
                </button>
            <% end %>  

        <% end %>
        
    </div>

    <!-- MIDDLE SPACE -->

    <div class="col-md-1"></div>

    <!-- RIGHT PANEL -->

    <div class="col-md-3 related-articles-section" align="middle">
        <h3>Related Articles</h3>

        <% @better_related_articles.each do |related| %>

            <div class="col-md-12 article-mini" align-self="middle">
                <div class="article-mini-img" onclick="location.href='/articles/<%= related.id %>';" style="cursor: pointer;">
                    <%= image_tag related.img_src, class: "article-rel" %>
                </div>
                <h5 class="article-mini-headline" onclick="location.href='/articles/<%= related.id %>';" style="cursor: pointer;" ><%= related.headline %></h5>
                <p class="article-mini-date">
                    <i class="far fa-clock"></i><span class="date"> <%= related.created_at.strftime("%d %B %Y") %></span> | 
                    <%= link_to @related_category, articles_path(category: @related_category), class: "article-mini-category", style: "font-weight: 400;" %>
                </p>
            </div>

        <% end %>

    </div>
</div>

<br><br>

<!-- ARTICLE STATS -->

<div class="row row-article-stats article-info">
    <div class="col-md-4 col-article-info" align="left">
        <p class="p-stats">Category: <strong><%= @article.category.name %></strong></p>
        <p class="p-stats">Keywords: 
            <strong>
                <% @article.keywords.each_with_index do |keyword, index| %>
                    <% if index != @article.keywords.count - 1%>
                        <%= keyword.name%>,   
                    <% else %>
                        <%= keyword.name%>
                    <% end %>
                <% end %>
            </strong>
        </p>
    </div>

    <div class="col-md-8 col-article-stats" align="left">
        <p class="p-stats">Views: <strong><%= @article.views %></strong></p>
        <p class="p-stats">Likes: <strong class="article-stats-likes"><%= @article.cached_votes_up %></strong></p>
    </div>
</div>

<br><br>