config/routes.rb
Rails.application.routes.draw do
  # READER ROUTES

  devise_for :readers

  resources :articles do
    member do
      put 'like' => 'articles#vote'
    end
  end

  get 'history' => 'articles#history'
  get 'friends' => 'articles#friends'

  get 'readers/:reader_id/articles' => 'articles#index_personal', as: 'personal_articles'
  get 'readers/:reader_id/articles/:article_id' => 'personal_articles#show', as: 'personal_article'

  # ADMIN ROUTES

  devise_for :admins

  resources :statistics

  get 'statistics/readers/:reader_id' => 'statistics#readers', as: 'statistics_reader'
  get 'statistics/readers/:reader_id/preferences/:preference_id' => 'statistics#preferences', as: 'statistics_reader_preference'
  get 'statistics/readers/:reader_id/preferences/:preference_id/keywords/:keyword_id' => 'statistics#keywords', as: 'statistics_reader_keyword'

  # ROOT PATH

  root 'articles#index'
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :require_login
  before_action :find_reader, only: %i[readers preferences keywords]
  before_action :find_preference, only: %i[preferences keywords]
  before_action :find_word, only: [:keywords]
  respond_to :js, :json, :html

  def index

    @readers = Reader.all

    @keywords = Keyword.where(word_type: "Preference").order(name: :asc)

    categories_to_normalize = Category.order(relevance: :desc).limit(10)

    max_relevance_keyword = @keywords.group(:name).sum(:relevance).values.max
    max_relevance_category = categories_to_normalize.sum(:relevance)
  
    normalizer = StatisticsHelper::Normalizer.new
    normalizer.normalize(@keywords, max_relevance_keyword)
    normalizer.normalize(categories_to_normalize, max_relevance_category)

    @categories = Category.order(preferencial_score: :desc).take(10)

    @topics = Keyword.where(word_type: "Preference").group(:name).sum(:relevance).sort_by { |name, relevance, id| relevance}.reverse[0..19]
    
    @heigth = 15*Keyword.where(word_type: "Preference").count + 50

    @data = @categories.map { |c| [c.name, c.preferencial_score] }.to_h

  end

  def readers
    @preferences = @reader.preferences.order(relevance: :desc)

    @orders = @reader.orders

    @articles = Article.where(reader_id: @reader.id)

    @keywords = Keyword.where(reader_id: @reader.id).order(name: :asc)

    @heigth = 15*@keywords.count + 50

    max_relevance = @keywords.group(:name).sum(:relevance).values.max

    normalizer = StatisticsHelper::Normalizer.new
    normalizer.normalize(@keywords, max_relevance)
    normalizer.normalize(@preferences, @preferences.sum(:relevance))

  end

  def preferences
    @keywords = @reader.preferences.find_by(id: @preference.id).keywords.order(name: :asc)

    max_relevance = @keywords.group(:name).sum(:relevance).values.max

    normalizer = StatisticsHelper::Normalizer.new
    normalizer.normalize(@keywords, max_relevance)

    category_id = Category.find_by(name: @preference.category).id

    @categorised_orders = @reader.orders.where(category_id: category_id)

    @heigth = 15*@keywords.count + 50

  end


  def keywords

  end

  private

  def require_login
    redirect_to new_admin_session_path unless admin_signed_in?
  end

  def find_reader
    @reader = Reader.find(params[:reader_id])
  end

  def find_preference
    @preference = Preference.find(params[:preference_id])
  end

  def find_word
    @word = Keyword.find(params[:keyword_id])
  end
end

app/helpers/statistics_helper.rb
# frozen_string_literal: true

module StatisticsHelper
	class Normalizer
		
    def normalize(objects, max_relevance)
      objects.each do |object|
        rescale(object, max_relevance)
      end
    end

    private

    def rescale(object, max)
      x = object.relevance
      z = (x / max.to_f) * 100
      object.preferencial_score = z.round(2)
      object.save
		end

  end

	class Analyzer
		
		def trending(keyword_name)
			# Get keyword usage over time
      group = KeywordStatistic.where(name: keyword_name)
                              .group(:id)
                              .group_by_day(:created_at)

			# Get keyword hits for today
			x = group.where('created_at > ?', 1.days.ago).count.size
			
			# Get keyword hits for two days ago
      y = group.where(created_at: 2.days.ago..1.days.ago).count.size

      growth_rate(x.to_f, y.to_f) > 20.00
		end

		def compute_similarity(friendships)
			friendships.each do |friendship|
				reader1 = Reader.find(friendship.reader_id)
				reader2 = Reader.find(friendship.friend_id)
				similarity(reader1, reader2)
			end
		end

    private 

    def growth_rate(x, y)
      # Growth died
      if x == 0 || y == 0
        0
      else
        rate = (((x - y) / y) * 100).round(2)
      end
		end
		
		def similarity(reader1, reader2)
      # Get all category-preferences for each reader
      reader1_c = reader1.preferences
			reader2_c = reader2.preferences

			friendship = reader1.friendships.find_by(friend_id: reader2.id)
			
			return false if reader1_c.count == 0 || reader2_c.count == 0

      # Get all keyword-preferences for each reader
      reader1_k = Keyword.where(reader_id: reader1.id)
                         .group(:name)
                         .sum(:preferencial_score)
      reader2_k = Keyword.where(reader_id: reader2.id)
                         .group(:name)
                         .sum(:preferencial_score)

      # Get all global preferences
      all_p = Preference.select(:category).distinct
      all_k = Keyword.where(word_type: 'Preference')
                     .select(:name).distinct

      # Initialize arrays used for categories (a & b) and for keywords (c & d)
      a,b,c,d = [],[],[],[]

      all_p.each_with_index do |p, index|
        p1 = reader1_c.find_by(category: p.category)
        p2 = reader2_c.find_by(category: p.category)
        a[index] = preferencial_score(p1)
        b[index] = preferencial_score(p2)
      end

      all_k.each_with_index do |k, index|
        k1 = reader1_k[k.name]
        k2 = reader2_k[k.name]
        c[index] = valid_score(k1)
        d[index] = valid_score(k2)
			end
			
			friendship.temp_distance = (euclidean_distance(a,b) + euclidean_distance(c,d)) / 2
			friendship.save
			friendship.distance = rescale(friendship.temp_distance, Friendship.maximum(:temp_distance))
			friendship.similarity = (100 - friendship.distance)
			friendship.save
    end

    def euclidean_distance(a, b)
      distance = axis(a, b, 0)
      Math.sqrt(distance)
    end

    def axis(a, b, index)
      return false if a[0].nil? || b[0].nil? || a.size != b.size
      return 0 if a[index].nil?
      axis_distance = (b[index] - a[index])**2
      axis_distance += axis(a, b, index + 1)
    end

    def preferencial_score(p)
      return 0 if p.nil?
      p.preferencial_score
    end

    def valid_score(k)
      return 0 if k.nil?
      k
		end
		
		def rescale(var, max)
      return ((var / max.to_f) * 100).round(2)
		end

  end
end

app/views/statistics/index.html.erb
<h1 class="current-category">Global Statistics</h1>

<br>

<h3>Readers (<%= @readers.count %>)</h3>

<div class="row row-readers">

    <% @readers.each do |reader| %>

        <!-- Reader Bar -->

        <div class="col-md-2 col-reader">

            <br><br>


            <div class="reader-bar" onclick="location.href='statistics/readers/<%= reader.id %>';" style="cursor:pointer;" >
                <%= image_tag reader.avatar, class: "avatar-friend" %>
                <div class="reader-bar-text">
                    <h3 class="reader-name"><%= reader.name %></h3>
                </div>
            </div>
            
            <br>
    

        </div>

    <% end %> 

</div>

<br>

<h3>Reading Frequency</h3>
<p>(based on <b><%= Order.count %></b> articles read globally)</p><br>

<div class="col-md-12">

    <%= line_chart Reader.all.map { |reader|
        {name: reader.name, data: reader.orders.group_by_day(:created_at).count}
    }, legend: :left, ytitle: "Articles" %> <br><br>

</div>

<h3>Reading Patterns per Category</h3><br><br>
<div class="col-md-12">
    <%= line_chart @categories.map { |category|
        {name: category.name, data: Order.where(category_id: category.id).group_by_day(:created_at).count}
    }, legend: :left, ytitle: "Articles" %> <br><br>
</div>

<h3>Reading Patterns per Topics</h3><br><br>
<div class="col-md-12">
    <%= line_chart @topics.map { |topic|
        {name: topic.first, data: KeywordStatistic.where(name: topic.first).group_by_day(:created_at).count}
    }, legend: :left, ytitle: "Articles" %> <br><br>
</div>


<h3>Category Relevance</h3>
<p>(based on <b><%= @readers.count %></b> readers and <b><%= Order.count %></b> articles read globally)</p>

<br>

<div class="col-md-12 col-preferences">

    <%= pie_chart @data, donut: true, legend: :left %>

</div>

<h3>Topic Relevance</h3>
<br>

<div class="col-md-12 col-keywords">
    <%= bar_chart @keywords.group(:name).sum(:preferencial_score), colors: ["#57f", "#666"], min: 0, max: 100, width: "90%", height: "#{@heigth}px", xtitle: "Relevance (Global average)", label: "Relevance"%>
</div>

app/views/statistics/keywords.html.erb
<div class="col-md-12 col-reader-statistics">

    <div class="reader-bar">
        <%= image_tag @reader.avatar, class: "avatar-friend" %>
        <div class="reader-bar-text">
            <h3 style="cursor:pointer; margin-bottom: 2px;">
                <%= link_to  @reader.name, statistics_reader_path(@reader.id) %>
            </h3>
            <p>Preference: 
                <strong class="red-word">
                    <%= @word.name %> 
                </strong>
                within
                <strong class="purple-word">
                    <%= @preference.category %>
                </strong>
            </p><br>
        </div>
    </div>

</div>

<h3>Total Articles Read: <%= KeywordStatistic.where(:keyword_id => @word.id).count %></h3> <br>


<div class="col-md-12">

    <%= line_chart KeywordStatistic.where(:keyword_id => @word.id).group_by_day(:created_at).count, colors: ["#f70439", "#666"],label: "Articles" %>

</div>

app/views/statistics/preferences.html.erb
<div class="col-md-12 col-reader-statistics">

    <div class="reader-bar">
        <%= image_tag @reader.avatar, class: "avatar-friend" %>
        <div class="reader-bar-text">
            <h3>
                <h3 style="cursor:pointer; margin-bottom: 2px;">
                    <%= link_to  @reader.name, statistics_reader_path(@reader.id) %>
                </h3>
                <p>Preference: 
                    <strong class="purple-word">
                        <%=@preference.category%>
                    </strong>
                </p><br>
            </h3>
        </div>
    </div>

</div>

<br>

<h3>Total Articles Read: <%=@categorised_orders.count%></h3><br>

<br>

<div class="col-md-12">

    <%= line_chart @categorised_orders.group_by_day(:created_at).count, colors: ["#93f", "#666"], ytitle: "Articles", label: "Articles" %><br><br>

</div>

<h3>Topics in this Category: <%= @keywords.count %></h3><br>

<div class="col-md-12">

    <%= bar_chart @keywords.group(:name).sum(:preferencial_score), colors: ["#93f", "#666"], min: 0, max: 100, width: "90%", height: "#{@heigth+30}px", label: "Relevance" %> <br><br>

</div>

<h3>Reading Pattern for Topics</h3><br><br>

<div class="col-md-12">

    <% @set_of_keywords = @keywords.group(:id).order('max(relevance) DESC').limit(10)%>

    <%= line_chart @set_of_keywords.all.map { |keyword|
        {name: keyword.name, data: KeywordStatistic.where(keyword_id: keyword.id).group_by_day(:created_at).count}
    }, legend: :left %>

</div>

app/views/statistics/readers.html.erb
<div class="col-md-12 col-reader-statistics">

    <div class="reader-bar">
        <%= image_tag @reader.avatar, class: "avatar-friend" %>
        <div class="reader-bar-text">
            <h3 class="reader-name" style="margin-bottom: 2px;"><%= @reader.name %></h3>
            <p>Preference: 
                <strong class="purple-word">
                    All
                </strong>
            </p><br>
        </div>
    </div>

</div>

<div class="statistics-reader-title">
    <h3>Preference Set</h3>
    <p style="margin: 0px 0px 25px 10px; font-size: 11px;"><i>(Based on <b><%= @reader.orders.count %></b> articles read)</i></p>
</div>

<div class="col-md-12 preference-panel">

    <div class="col-md-12 col-keywords">

        <% @preferences.each do |preference| %>

            <div class="col-md-3 preference-box category-box">

                <h4 class="preference-name category" onclick="location.href='/statistics/readers/<%=@reader.id%>/preferences/<%=preference.id%>';" >
                    <%= preference.category %> 
                    <span class="badge badge-light preference" style="margin: 5px;">
                        <%= preference.preferencial_score %>%
                    </span>
                </h4>

                <% preference.keywords.order(relevance: :desc).take(4).each do |keyword| %>

                    <div class="preference-box word-box" onclick="location.href='/statistics/readers/<%=@reader.id%>/preferences/<%=preference.id%>/keywords/<%=keyword.id%>';">
                        <h6 style="font-size: 11px;"><%= keyword.name[0..22]%> <span class="badge badge-light keyword" style="float: right;"><%= keyword.preferencial_score.to_i %></span></h6>
                    </div>          

                <% end %>

                <% unless (preference.keywords.count - 4) <= 0 %>

                    <div class="preference-box word-box" onclick="location.href='/statistics/readers/<%=@reader.id%>/preferences/<%=preference.id%>';">
                        <h6 style="font-size: 11px;"><u><%= (preference.keywords.count - 4) %> more topics</u></h6>
                    </div>

                <% end %>

            </div>

        <% end %>

    </div>

</div>

<h3><%=@reader.name%>'s Reading Pattern</h3><br><br>

<div class="col-md-12">
    <%= line_chart @preferences.all.map { |preference|
        {name: preference.category, data: @orders.where(category_id: Category.find_by(name: preference.category).id).group_by_day(:created_at).count}
    }, legend: :left, ytitle: "Articles", width: "90%" %> <br><br>
</div>

<h3><%=@reader.name%>'s Interests</h3><br><br>

<div class="col-md-12">
    <%= bar_chart @keywords.group(:name).sum(:preferencial_score), colors: ["#f70439", "#666"], min: 0, max: 100, width: "90%", height: "#{@heigth}px", xtitle: "Relevance", label: "Relevance" %> <br><br>
</div>

<h3>Suggestion Pattern for <%=@reader.name%></h3><br><br>

<div class="col-md-12">

    <%= line_chart @preferences.all.map { |preference|
        {name: preference.category, data: @articles.where(category_id: Category.find_by(name: preference.category).id).group_by_day(:created_at).count}
    }, legend: :left, ytitle: "Articles", width: "90%"  %>

</div>